Загрузите данные из файла Pokemon.csv в Excel. Сколько всего строк с номером (#) 18 в этом наборе? * Ответ 2

In [92]:
import pandas as pd
pokemon = pd.read_csv('Pokemon.csv')
pokemon.loc[pokemon['#'] == 18]

pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Выберите из набора исходных данных о покемонах всех покемонов со свойством Fighting. Сохраните выборку в отдельный файл Pokemon-Fighting.csv. Сколько всего боевых (Fighting) покемонов в наборе? * Ответ 53

In [98]:
len(pokemon[(pokemon['Type 1'] == 'Fighting') | (pokemon['Type 2'] == 'Fighting')])

53

Сколько летающих (Flying) покемонов среди обычных покемонов (Normal)? * Ответ 24

In [17]:
len(pokemon.loc[(pokemon['Type 1'] == 'Normal') & (pokemon['Type 2'] == 'Flying')])
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Переупорядочите набор исходных данных о покемонах, выделив группы по полю поколений (Generation), при этом в каждой группе следует упорядочить покемонов по возрастанию уровня здоровья (HP). Сохраните результат в файле Sorted-Groups-Pokemon.csv. Сколько покемонов шестого поколения имеют максимальное значение HP в этой группе? * Ответ 2

In [27]:
pokemon.loc[pokemon['Generation'] == 6]['HP'].sort_values()

732     38
727     38
721     40
790     40
724     41
      ...
794    108
769    123
741    123
792    126
793    126
Name: HP, Length: 82, dtype: int64

Укажите количество жуков (Bug) (по основному типу Type 1), которые являются ядовитыми(Type 2 = Poison) * Ответ 12

In [37]:
len(pokemon.loc[(pokemon['Type 1'] == 'Bug') & (pokemon['Type 2'] == 'Poison')])
pokemon

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

Укажите имя каменного покемона (Type 1 = Bug) с наименьшим значением атаки (Attack) * Ответ Shuckle

In [47]:
pokemon.loc[pokemon['Type 1'] == 'Bug']['Attack'].sort_values()
pokemon.iloc[230]

#                 213
Name          Shuckle
Type 1            Bug
Type 2           Rock
Total             505
HP                 20
Attack             10
Defense           230
Sp. Atk            10
Sp. Def           230
Speed               5
Generation          2
Legendary       False
Name: 230, dtype: object

Сколько покемонов со здоровьем (HP) 50 имеют уровень атаки (Attack) больше 100, но меньше 150? *

In [99]:
len(pokemon[(pokemon['HP'] == 50) & (pokemon['Attack'] > 100) & (pokemon['Attack'] < 150)])

3

Сформируйте выборку покемонов, не имеющих дополнительных особенностей (Type 2 отсутствует), сохраните её в файл Clear-Pokemon.csv Укажите среднее значение защиты (Defense) покемонов этой группы (в ответе укажите только целую часть, отбросив десятичную без округлений). * Ответ 73

In [80]:
pokemon_null = pokemon[pokemon['Type 2'].isnull()]
pokemon['Defense'].mean()

73.8425

Укажите максимальное значение скорости (Speed) для покемонов из выборки, сохранённой в Clear-Pokemon.csv * Ответ 180

In [56]:
pokemon_null['Speed'].max()

180

Укажите имя легендарного покемона из выборки, сохранённой в Clear-Pokemon.csv, из первого поколения (Generation) с минимальным значением атаки (Attack)? *
Ответ Mewtwo

In [91]:
a = pokemon_null[(pokemon_null['Generation'] == 1) & (pokemon_null['Legendary'] == True)]['Attack'].min()

pokemon_null[(pokemon_null["Attack"] == a) & (pokemon_null["Generation"] == 1)]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
64,59,Arcanine,Fire,NaN,555,90,110,80,100,80,95,1,False
155,143,Snorlax,Normal,NaN,540,160,110,65,65,110,30,1,False
162,150,Mewtwo,Psychic,NaN,680,106,110,90,154,90,130,1,True